# Generated by Django 5.1.7 on 2025-04-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paypal_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
