# Generated by Django 5.1.7 on 2025-04-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_chatbotfaq_chatbotconversation_chatbotmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'ELECTRONICS'), ('Home', 'HOME'), ('Clothings', 'CLOTHINGS')], max_length=15, null=True),
        ),
    ]
